lib/pg_search/multisearch/rebuilder.rb
spec/lib/pg_search/multisearch/rebuilder_spec.rb

Iterate over each record with `find_each` instead.
Fixes #70

Don’t use SQL to rebuild dynamic multisearchable

---

lib/pg_search/multisearch/rebuilder.rb
spec/lib/pg_search_spec.rb

We're using this gem and it's proven really useful, but we ran into a couple of problems with the standard multisearch document builder due to our STI models.
This pull request checks the model's inheritance_column instead of the existence of the 'type' column. It's important to check for two reasons:
* models might use a field other than "type" for inheritance (covered in a test)
* the model's table may have a "type" column that is not for Rails STI, so they set inheritance_column to nil (our situation)
I'm getting Rubocop problems on Travis, but not in files that I edited? Let me know what I can do to make this PR better.

Support STI models using self.inheritance_column

---

lib/pg_search/features/feature.rb
lib/pg_search/features/trigram.rb
lib/pg_search/features/tsearch.rb

I thought it would be nice to assert valid options for features, so that people know when they've made a typo. For example, since English is not my native language, I accidentally gave `:treshold` instead of `:threshold` to the Trigram feature. So it took me a while to figure out what was wrong.
I didn't write tests, because I didn't really find it a feature that would need to be tested (nothing will brake if it stops working).
Lastly, I really want to thank you for this awesome gem. It's really a perfect wrapper for full-text search; while there are great defaults, it's also *very* configurable. It's really easy now to use PostgeSQL for full-text search.

Assert valid options for features

---

lib/pg_search/scope_options.rb
spec/integration/pg_search_spec.rb

This patch include two spec examples, one for the simple case of chaining
scopes and the other for the case where two relations are being merged.
To fix the first issue, I've expanded on @davearonson solution by using
an instance variable in the given scope instead of a class variable. To
prevent polluting the given relation, the code spawn a new relation if
the variable is missing.
Using this variable as a counter the pg_search scope pseudo-table is
aliased with the current count as a suffix if it's not the first
one. This let us not having to dynamically generate the
`with_pg_search_rank` method which use the first scope for rank.
Finally to fix merged relations, the table name is used in the pg_search
scope pseudo-table aliases.
Given the following AR query:
```ruby
> …
```

Enable chaining of pg_search scopes

---

README.md
lib/pg_search/scope_options.rb
spec/integration/pg_search_spec.rb

This is a followup to issue #1.  The changes introduced to resolve that issue made a fairly significant breaking change: the search rank subquery no longer has a consistent name.  For uses of PgSearch with complex queries, particularly queries that require GROUP BY clauses, you need the name of the subquery.  Unfortunately, the code that generates the alias for the subquery was buried as a private method in ScopeOptions.
This series of commits makes the generation of the subquery alias more consistent, makes it publicly available by re-using the already available `.alias` method on the PgSearch::Configuration class, eliminates some access control violations, and updates the documentation to more correctly describe what's going on with pg_search_rank.
Importantly, these changes do not …

Clean up rank table aliasing

---

lib/pg_search/scope_options.rb
spec/integration/pg_search_spec.rb

Currently using pg_search_rank along with a join fails due to id column collision of the two tables. Here's the fix for that with working specs.

pg_search_rank with join fixed with spec

---

README.md

linked to #278 - add a note to the readme outlining the query implications of setting a threshold query for trigram searching.
I agree it'd be nicer to have the similarity query hit the index but in the meantime letting users know that the index will be skipped should suffice.

add note about trigram thresholds and indexes

---

README.md
lib/pg_search.rb
lib/pg_search/features/tsearch.rb
lib/pg_search/scope_options.rb
spec/integration/pg_search_spec.rb

Basically I adapted https://github.com/Casecommons/pg_search/pull/211

Return highlighted excerpt of result (again)

---

README.md

Hello @nertzy 
It took me a couple of hours to figure how to do a composite count for each searchable_type it and as I see some issues relating count I thought this example would eventually become handy to other folks in the future.
As you encouraged in #180 ([here](https://github.com/Casecommons/pg_search/issues/180#issuecomment-46340091)), I am sending this pull request as it is probably going to clarify both count and group scenarios in one place.
Hope it helps!

Add total count for group by searchable_type example

---

lib/pg_search/configuration/association.rb
spec/lib/pg_search/configuration/association_spec.rb

This change disables the use of `string_agg` and `group by` for has_one/belongs_to associations when using `associated_against`. It was inspired by the following comment: https://github.com/Casecommons/pg_search/issues/51#issuecomment-7734106
This slightly improves the performance of using `associated_against` with has_one/belongs_to associations.

don't use string_agg for has_one/belongs_to associations

---

lib/pg_search/configuration.rb
lib/pg_search/configuration/association.rb
lib/pg_search/features/tsearch.rb
spec/lib/pg_search/configuration/association_spec.rb

Calling protected methods on connection object breaks interoperability and causes issues with other gems e.g `activerecord_autoreplica`. We can access the same value over public method: `raw_connection.server_version`.

avoid calling protected methods on connection object

---

lib/pg_search/railtie.rb

This file was removed in a previous commit and the line requiring it is now causing a large error in applications attempting to use pg_search v2.

Remove require 'pg_search/migration/associated_against_generator'

---

lib/pg_search.rb

Loading the PgSearch::Document model without waiting for ActiveRecord to
load can cause problems because it causes ActiveRecord to pull
configuration into ActiveRecord::Base before the initializers get
loaded. This means ActiveRecord::Base could accidentally have inaccurate
configuration.
The fix for this is to wait until ActiveRecord has fully loaded before
requiring the model.
ref: rails/rails#23589

Wait to load PgSearch::Document until after ActiveRecord has loaded

---

lib/pg_search/features/tsearch.rb
spec/lib/pg_search/features/tsearch_spec.rb

Hi,
We a re using pg_search with languages and we are notice that the resulting snippets are not wrapped with tags if a dictionary is selected.
I am using pg_search 1.0.6, ruby 2.3.1 and active_record 4.2.4
A minimal script that reproduces the problem:
``` ruby
require 'active_record'
require 'pg_search'
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection(
adapter: 'postgresql',
database: 'problem',
username: 'user',
password: 'password'
)
unless ActiveRecord::Base.connection.table_exists?(:tests)
ActiveRecord::Base.connection.create_table :tests do |t|
t.text :body
end
end
class Test < ActiveRecord::Base
include PgSearch
pg_search_scope :search_es,
against: :body,
using: {
tsearch: {
dictionary: 'spanish',
highlight: {
start_sel: '<b>',
stop_sel: '</b>' …
```

Fixed highlight problem when a stemming dictionary is configured.

---

lib/pg_search/migration/generator.rb
lib/pg_search/migration/templates/add_pg_search_dmetaphone_support_functions.rb.erb
lib/pg_search/migration/templates/create_pg_search_documents.rb.erb

Reported in Casecommons/pg_search/issues/361
Include the Rails major and minor version to the inherited `ActiveRecord::Migration` class, when generating migrations within a Rails app version 5 or greater.
Raises when `ActiveRecord::Migration` is inherited directly:  https://github.com/rails/rails/commit/249f71a22ab21c03915da5606a063d321f04d4d3

Add Rails version to generated migrations

---

.travis.yml
lib/pg_search/features/tsearch.rb
spec/integration/pg_search_spec.rb

This is a failing test for a bug we ran into: when searching on an unaccented pg_search_scope for a query which includes `‘`, an invalid expression is generated:
```
ActiveRecord::StatementInvalid:
PG::SyntaxError: ERROR:  syntax error in tsquery: "' L'Content '"
: SELECT "with_model_model_with_pg_searches_57799_70174002903340".* FROM "with_model_model_with_pg_searches_57799_70174002903340" INNER JOIN (SELECT "with_model_model_with_pg_searches_57799_70174002903340"."id" AS pg_search_id, (ts_rank((to_tsvector('simple', unaccent(coalesce("with_model_model_with_pg_searches_57799_70174002903340"."title"::text, '')))), (to_tsquery('simple', ''' ' || unaccent('L‘Content') || ' ''')), 0)) AS rank FROM "with_model_model_with_pg_searches_57799_70174002903340" WHERE (((to_tsvector('simple', …
```

Add failing spec for invalid tsquery generation

---

README.md

The `tsvector` column [is a supported type](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L100) in ActiveRecord 4.2+, so the instructions that require the reader to change the schema format to SQL are incorrect. You can still use the `schema.rb` file when your PostgreSQL database contains a column of type `tsvector`.

Remove outdated instructions about the tsvector column type

---

README.md

There are additional undocumented options for multisearch now (update_if and additional_attributes) that should be included in the documentation. Included them here and added small examples. related to PR #293. Note, there is still a small bug with the additional_attributes that is waiting to be fixed in PR #317 -- a workaround is noted here.

Update documentation for multisearch options

---

README.md

- changed hash syntax (https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#hashes)
- in highlight section changed `<start>` and `<stop>` tag to `<b>` and `</b>` to match an example bellow this section (https://github.com/Casecommons/pg_search/pull/402/files#diff-04c6e90faac2675aa89e2176d2eec7d8R749)

docs: enhance documentation

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.7.0**.
[JRuby 9.2.7.0 release blog post](https://www.jruby.org/2019/04/09/jruby-9-2-7-0.html)
- The Travis setting `sudo: false` has been removed - See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

CI: Use JRuby 9.2.7.0, drop unused sudo: false

---

.travis.yml

This PR updates the used `ACTIVE_RECORD_VERSION` for Rails 6 to `6.0.0`.

CI: Use Rails 6.0.0 branch

---

.travis.yml

This PR only updates the CI matrix to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known
- the choice of jdk avoids a lot of settings needed for later JVMs

CI: Update to latest Rubies, use openjdk8

---

README.md

I think the reference / foreign key attribute from example should have index added to it. It's used in `where` query and it references another table.
This will make searches in that case faster. (Disclaimer: I didn't run any perf tests for this)

Add index to additional reference attribute

---

lib/pg_search.rb

If you use pg_search in a non-rails project what uses `actionmailer` the project fails to load because [actionmailer uses actionview](https://github.com/rails/rails/blob/f741f56da3712b943b5584d03df661fc38aa7169/actionmailer/actionmailer.gemspec#L37) what [uses rails-html-sanitizer](https://github.com/rails/rails/blob/f741f56da3712b943b5584d03df661fc38aa7169/actionview/actionview.gemspec#L39) what defines [`Rails` namespace](https://github.com/rails/rails-html-sanitizer/blob/51dc564c6509201070f72456bb2c13f87bb373d6/lib/rails-html-sanitizer.rb#L6) though it doesn't have `Railtie` in it.

fix(railtie dependency): check the existence of Railtie in Rails namespace before requiring it

---

.rubocop.yml
lib/pg_search.rb
lib/pg_search/model.rb
pg_search.gemspec
spec/lib/pg_search_spec.rb

This reverts commit 7ff41966026d990db95cda8ad4414f33264e734d.
Fixes #446. Users were reporting problems after this PR using multithreaded servers like puma. I decided to revert the whole commit because except for the trailing whitespace that was removed, all that `rubocop-thread_safety` would achieve is that we'd have to add ignore comments.
Sadly I was unable to write a failing test for this in our own system, even with system tests that use puma as their webserver. I'd have to check if puma settings are somehow different in development and test and in which way. Others have also reported that this was [the case](https://github.com/Casecommons/pg_search/issues/446#issuecomment-696089239)
For reproduction steps to reproduce the error with even simple setups, see …

Fixes #446, enable usage of pg_search with multithreaded servers like puma

---

README.md

Hello, I'd like to suggest a set of links for all the sub sections within [Usage](https://github.com/Casecommons/pg_search#usage), to help people navigate the README file when they know roughly what they're looking for, or are looking to understand the scope of functionality on offer.
I appreciate it will add a small maintenance overhead as documentation is added/updated, but that should only be a minor chore. 
Thanks

Added contents links for Usage section of README

---

README.md

While setting up multisearch I noticed what I believe to be a little error in the documentation:
```ruby
PgSearch::Document.delete_all(searchable_type: "TheModel")
PgSearch::Document.delete_by(searchable_type: "TheModel")
```

Change delete_all to delete_by in README.md

---

lib/pg_search/scope_options.rb
spec/integration/pg_search_spec.rb

Hello,
I have recently started experimenting with postgres' full-text search capabilities. So far, the experience I've had with *pg_seach* has been very pleasant so kudos to the maintainers of this nice library 🙂👏 
I've been doing my experiments on a large set of data that closely mimics what we have in production, which made me realize that it would be best if I could `select()` a limited set of columns for performance reasons, which – if I'm not mistaken – is currently not possible when using the scope `::with_pg_search_highlight`.
This PR is a proposal to implement a similar logic than what is currently performed in `::with_pg_search_rank`'s definition. Apologies in advance if I've missed the reason why it was decided not to implement this behaviour in `::with_pg_search_highlight`.

Preserve column selection when chaining ::with_pg_search_highlight

---

README.md

The provided double-pipe concatenation example has a gotcha regarding handling of NULL values, which can result in an "unexpected" empty `content` value. 
I've swapped this for a use of `CONCAT_WS()` which is more forgiving/readable, and has been supported since Postgres 9.1 (released 10 years ago). A note has been added for those unfortunate enough to be working on very old databases. Maybe this isn't even necessary, but some might consider the concatenation more "proper".

Update multisearch README rebuild example

---

README.md
lib/pg_search/multisearch.rb
spec/lib/pg_search/multisearch_spec.rb

The rebuild process can be pretty time-consuming with a large number of rows, or even if you use dynamic attributes. For that reason, clients should have the option of running the process outside of a transaction.

Optionally disable transaction when rebuilding documents

---

lib/pg_search/configuration.rb
spec/integration/pg_search_spec.rb

I've only been using the gem a short time, so I could be missing a use case where this change doesn't make sense.
It seems to me like if you're using a tsvector column, you don't need to specify `against`. Keeping the `against` option specified isn't a big deal, but it does mean that you need to keep it up-to-date with whatever populates the tsv column, which is a little strange.

Don't require against if tsvector_column is specified

---

lib/pg_search/features/tsearch.rb
spec/integration/pg_search_spec.rb

Added U+02BB/U+02BC quotes to `DISALLOWED_TSQUERY_CHARACTERS` otherwise get an error
`PG::SyntaxError: ERROR: syntax error in tsquery:`
p.s. Does it make sense to add PgSearch configurator to provide an ability to set this characters outside the gem?

Add U+02BB/U+02BC to disallow tsquery characters

---

README.md

#454 made some changes to the readme to replace `delete_all` with `delete_by`, but one instance remains and this PR updates that
The current readme has an example for multisearch's `update_if` using the ActiveRecord `*_changed?` method to determine if the pg search document should be updated. However, because `update_if` is evaluated in an `after_save` callback the dirty flags have already been cleared which may result in pg search documents not being updated as expected. Instead, I'd suggest people use `*_previously_changed?` as it returns whether the attribute was changed before the model was saved is more useful for more cases.
There are some whitespace changes included in this PR which I can remove if you'd prefer.

Readme updates for delete_by and update_if option

---

lib/pg_search/configuration/column.rb
spec/lib/pg_search/configuration/column_spec.rb
spec/lib/pg_search/features/dmetaphone_spec.rb
spec/lib/pg_search/features/trigram_spec.rb
spec/lib/pg_search/features/tsearch_spec.rb

This PR resolves #252, allowing for more more advanced columns, such as extracting elements out of json arrays, or fields out of json objects. This is intended to be entirely backward compatible.

column: add support for Arel::Nodes::SqlLiteral

---

.github/workflows/ci.yml
.rubocop.yml
README.md
pg_search.gemspec
spec/spec_helper.rb

Ruby 2.7 has been EOL since 2023-03-31

Drop support for Ruby 2.7

---

.github/workflows/ci.yml
README.md
pg_search.gemspec

Active Record 6.0 has been EOL since 2023-06-01

Drop support for Active Record 6.0

---

.github/workflows/ci.yml
lib/pg_search/scope_options.rb

The interface for `Or` arel node was changed in https://github.com/rails/rails/pull/51492.
This currently prevents our upgrade to rails 7.2.
Fixes #536.

Fix compatibility with ActiveRecord 7.2
